version: '3.8'

services:

  backend:
  
    build: .

    ports:
      - "8081:8081"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vishnu

    depends_on:
      - db


  db:

    image: postgres:latest

    container_name: postgres

    restart: always

    environment:
      - POSTGRES_PASSWORD=vishnu
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=postgres

    ports:
      - "5432:5432"
